<Project Sdk="Microsoft.NET.Sdk.Razor">

   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <Version>0.21.0</Version>
      <FileVersion>0.21.0</FileVersion>
      <AssemblyVersion>0.21.0</AssemblyVersion>
   </PropertyGroup>

   <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
   </ItemGroup>

   <ItemGroup>
      <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0" />
      <PackageReference Include="OrchardCore.Settings" Version="3.0.0" />
      <PackageReference Include="OrchardCore.Navigation" Version="3.0.0" />
      <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0" />
      <PackageReference Include="OrchardCore.Themes" Version="3.0.0" />
   </ItemGroup>

</Project>
